### ISSUE TITLE
Building and getting started for dummies

### ISSUE THREAD

**Issue by jmmcd** [eclab/seq#1]
I was able to build on MacOS by applying the changes (below) and then typing `make jar`.

```
diff --git a/Makefile b/Makefile
index 1bc7667..b9c945b 100644
--- a/Makefile
+++ b/Makefile
@@ -1,4 +1,4 @@
-JAVACFLAGS =
+JAVACFLAGS = -cp "./libraries/*"
 JAVAC = javac ${JAVACFLAGS}
 FLAGS = -g -Xlint:deprecation

@@ -54,8 +54,8 @@ jar: all
        touch /tmp/manifest.add
        rm /tmp/manifest.add
        echo "Main-Class: seq.gui.SeqUI" > /tmp/manifest.add
-       cd seq/libraries ; jar -xvf coremidi4j-1.6.jar ; jar -xvf json.jar ; jar -xvf flatlaf-3.3-20231031.152110-17.jar
-       mv seq/libraries/META-INF . ; mv seq/libraries/uk . ; mv seq/libraries/com . ; mv seq/libraries/org .
+       cd libraries ; jar -xvf coremidi4j-1.6.jar ; jar -xvf json.jar ; jar -xvf flatlaf-3.4.1.jar
+       mv libraries/META-INF . ; mv libraries/uk . ; mv libraries/com . ; mv libraries/org .
        jar -cvfm install/seq.jar /tmp/manifest.add `find seq -name "*.class"` `find seq -name "*.html"` `find seq -name "*.png"` `find seq -name "*.jpg"` uk/ META-INF/ org/ com/
        echo jar -cvfm install/seq.jar `find seq -name "*.class"` `find seq -name "*.html"` `find seq -name "*.png"` `find seq -name "*.jpg"` uk/ META-INF/ org/ com/
        rm -rf uk META-INF com org module-info.class
```

And then I can get started by typing `java -jar install/seq.jar`, and starting Logic, and selecting Logic's virtual MIDI-in as a `seq` MIDI out. Then clicking some notes in the step sequencer produces some audio in Logic.

**Comment by eclab** [comment]
I think this error is due to migration from our internal repoitory (not git) to github; in the process we moved the location of the Makefile relative to the seq directory.  Will fix it.

**Comment by eclab** [comment]
I've revised the Makefile to work properly with make jar.  Make install will work but only on Macs with earlier versions of Java (which use javapackager).  Have not yet gotten packaging working for Java 17 and up.  But you can at least build a single jar file which you can then run with **java -jar seq.jar**

**Comment by jmmcd** [comment]
Yes this works for me too
